### PR TITLE
Remove "fmt" dependency in js_notwasm.go

### PR DESCRIPTION
**Pull request by elliott5**
Reduces the generated JS for a small project by around 1Mb

### CODE REVIEW

**Review by hajimehoshi — APPROVED** [review]
lgtm, thank you!

**Comment by hajimehoshi** [comment]
Oh, you created this PR for `api` branch? `master` branch was also fine in this case.

**Comment by hajimehoshi** [comment]
@elliott5 I plan to squash all the commits in #3, so your commit would be integrated in it. It's ok if you are ok, but if you want to keep the commit in this Git repository, I'd recommend to create the same PR for `master` branch instead of `api` branch before merging #3.

**Comment by elliott5** [comment]
It's OK @hajimehoshi I've no desire to be famous ... squash away!

**Pull request merged**
